[debug] [2020-04-24T21:37:21.982Z] ----------------------------------------------------------------------
[debug] [2020-04-24T21:37:21.984Z] Command:       D:\Usuarios\uwu\Program Files\node.exe C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2020-04-24T21:37:21.985Z] CLI Version:   8.1.1
[debug] [2020-04-24T21:37:21.985Z] Platform:      win32
[debug] [2020-04-24T21:37:21.985Z] Node Version:  v12.16.2
[debug] [2020-04-24T21:37:21.986Z] Time:          Fri Apr 24 2020 16:37:21 GMT-0500 (GMT-05:00)
[debug] [2020-04-24T21:37:21.986Z] ----------------------------------------------------------------------
[debug] [2020-04-24T21:37:21.986Z] 
[debug] [2020-04-24T21:37:22.012Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-24T21:37:22.123Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-24T21:38:06.463Z] ----------------------------------------------------------------------
[debug] [2020-04-24T21:38:06.465Z] Command:       D:\Usuarios\uwu\Program Files\node.exe C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2020-04-24T21:38:06.465Z] CLI Version:   8.1.1
[debug] [2020-04-24T21:38:06.465Z] Platform:      win32
[debug] [2020-04-24T21:38:06.465Z] Node Version:  v12.16.2
[debug] [2020-04-24T21:38:06.466Z] Time:          Fri Apr 24 2020 16:38:06 GMT-0500 (GMT-05:00)
[debug] [2020-04-24T21:38:06.466Z] ----------------------------------------------------------------------
[debug] [2020-04-24T21:38:06.466Z] 
[debug] [2020-04-24T21:38:06.476Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-24T21:38:06.505Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-24T21:38:06.771Z] Error: EBUSY: resource busy or locked, rename 'C:\Users\57317\.config\configstore\firebase-tools.json.1734350340' -> 'C:\Users\57317\.config\configstore\firebase-tools.json'
    at Object.renameSync (fs.js:661:3)
    at Function.writeFileSync [as sync] (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\write-file-atomic\index.js:244:8)
    at Configstore.set all [as all] (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\configstore\index.js:61:20)
    at Configstore.set (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\configstore\index.js:91:12)
    at process.<anonymous> (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js:80:21)
    at process.emit (events.js:322:22)
    at process.exit (internal/process/per_thread.js:166:15)
    at Timeout._onTimeout (C:\Users\57317\AppData\Roaming\npm\node_modules\firebase-tools\lib\errorOut.js:19:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[error] 
[error] Error: An unexpected error has occurred.
